# Generated by Django 3.1.3 on 2023-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_auto_20230926_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
